spring:
  security:
    oauth2:
      client:
        registration:
          google :
            clientId:  423380677896-rm865b3kfb67s0pi4fesavt5hu3ecat1.apps.googleusercontent.com
            clientSecret: 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